Gruntfile.js

Required: https://github.com/agoravoting/agora-gui-common/pull/6

Changed avConfig version

---

avElection/layouts/election-links-directive/election-links-directive.html
avElection/layouts/election-links-directive/election-links-directive.js

* disable election links if home is disabled
* moving the complex logic that enables election links to a function
* fixing condition

Election links disabled home

---

avElection/ballot-locator-screen-directive/ballot-locator-screen-directive.html

There should be a single call to action on each screen. Normal buttons will be gray, and the CTA will be green.
* Revert the colors of the class `btn-success`to gray.
* Add a new class `btn-success-action` with the green color.
* Use it in the login screens.
This branch is being used at https://felix-dev.sequentech.io

Button colors

---

avElection/ballot-locator-screen-directive/ballot-locator-screen-directive.html

6.1.x version of [this PR](https://github.com/sequentech/election-portal/pull/149)

Change color of CTA buttons

---

avElection/layouts/default-election-directive/default-election-directive.less

[Same PR as this](https://github.com/sequentech/election-portal/pull/151), but for version 6.

Fix logo max height

---

avElection/public-controller/public-controller.less

[6.1.x version of this PR.](https://github.com/sequentech/election-portal/pull/153)

Fix padding on navbar

---

avElection/layouts/default-election-directive/default-election-directive.html
avElection/layouts/default-election-directive/default-election-directive.less

[See master PR](https://github.com/sequentech/election-portal/pull/155)

More mobile fixes (#155)

---

package.json
yarn.lock

Include changes to master [from this PR.](https://github.com/sequentech/election-portal/pull/159)

 Bump moment from 2.29.2 to 2.29.4 (6.1.x)

---

avElection/ballot-locator-screen-directive/ballot-locator-screen-directive.html
avElection/ballot-locator-screen-directive/ballot-locator-screen-directive.js
avElection/borda-results-directive/borda-results-directive.html
avElection/borda-results-directive/borda-results-directive.less
avElection/plurality-at-large-results-directive/plurality-at-large-results-directive.html
avElection/public-controller/public-controller.js
avElection/results-directive/results-directive.html
locales/ca.json
locales/en.json
locales/es.json
locales/fi.json
locales/gl.json
locales/nb.json
locales/sv.json

* Enable using enter to search the ballot.
* Correctly label the search input.
* Refactor, remove html from the locator status translations.
* Css fixes to wrap-word ballot hash.
* Replate table caption with table header on borda.
* Remove/comment out empty percentages column on plurality.
* Css changes to borda results to fix color contrast.
* Fix results auto-updating to only update on actual changes.
* Add aria-label translations to download config button and social share buttons.

improvements

---

Gruntfile.js

Parent issue: https://github.com/sequentech/meta/issues/68

favicon.ico not loading

---

Gruntfile.js

Parent issue: https://github.com/sequentech/meta/issues/68

favicon.ico not loading (#193)

---

app.js

Parent issue: https://github.com/sequentech/epi/issues/114

Alternative Auth methods support

---

app.js

Parent issue: https://github.com/sequentech/epi/issues/114

Alternative Auth methods support (#199)

---

SequentConfig.js

Parent issue: https://github.com/sequentech/epi/issues/19

✨ Countdown until logout

---

Gruntfile.js
SequentConfig.js
SequentPluginsConfig.js
index.html
package.json

Parent issue: https://github.com/sequentech/meta/issues/136
This reverts commit 21a24368377d590576da9a109b2bc71be0716d38.

`master` branch should be using `master` version number and not `8.0.0`

---

avElection/ballot-locator-screen-directive/ballot-locator-screen-directive.html
avElection/borda-results-directive/borda-results-directive.html
avElection/layouts/default-election-directive/default-election-directive.html
avElection/layouts/simple-question-directive/simple-question-directive.html
avElection/plurality-at-large-results-directive/plurality-at-large-results-directive.html
avElection/results-directive/results-directive.html
avElection/results-directive/results-directive.js
avElection/verify-results-directive/verify-results-directive.html

Parent issue: https://github.com/sequentech/meta/issues/122

✨ Multilingualism

---

avElection/layouts/default-election-directive/default-election-directive.html
avElection/layouts/default-election-directive/default-election-directive.less

Parent issue: https://github.com/sequentech/meta/issues/144

🐞 Duplicated header on election portal

---

avElection/layouts/default-election-directive/default-election-directive.html
avElection/layouts/default-election-directive/default-election-directive.less

Parent issue: https://github.com/sequentech/meta/issues/144

🐞 Duplicated header on election portal (#205)

---

avElection/public-controller/public-controller.js

Parent issue: https://github.com/sequentech/meta/issues/213

🐞 public page is active

---

avElection/public-controller/public-controller.js

Parent issue: https://github.com/sequentech/meta/issues/213

🐞 public page is active (#208)

---

package.json
yarn.lock

Parent issue: https://github.com/sequentech/meta/issues/230

Security updates (#210)

---

avElection/ballot-locator-screen-directive/ballot-locator-screen-directive.html
avElection/borda-results-directive/borda-results-directive.html
avElection/layouts/default-election-directive/default-election-directive.html
avElection/layouts/simple-question-directive/simple-question-directive.html
avElection/plurality-at-large-results-directive/plurality-at-large-results-directive.html
avElection/results-directive/results-directive.html
avElection/results-directive/results-directive.js
avElection/verify-results-directive/verify-results-directive.html

Parent issue: https://github.com/sequentech/meta/issues/122

✨ Multilingualism (#204)

---

avElection/public-controller/public-controller.js

Parent issue: https://github.com/sequentech/meta/issues/265

🐞 Login allowed with election closed

---

avElection/public-controller/public-controller.js

Parent issue: https://github.com/sequentech/meta/issues/265

🐞 Login allowed with election closed (#214)

---

avElection/public-controller/public-controller.js

Parent issue: https://github.com/sequentech/meta/issues/306

✨ Select languages per election

---

avElection/public-controller/public-controller.js

Parent issue: https://github.com/sequentech/meta/issues/306

✨ Select languages per election (#219)

---

Gruntfile.js
app.js
avElection/public-controller/public-controller.js

Parent issue: https://github.com/sequentech/meta/issues/315

🐞 default translation appears when switching language for the first time

---

app.js
avElection/layouts/simple-question-directive/simple-question-directive.js
avElection/results-directive/results-directive.js

Parent issue: https://github.com/sequentech/meta/issues/315

🐞 default translation appears when switching language for the first time (#223)

---

avElection/public-controller/public-controller.js

Parent issue: https://github.com/sequentech/meta/issues/331

✨ login page: no redirection if election hasn't started

---

avElection/public-controller/public-controller.js

Parent issue: https://github.com/sequentech/meta/issues/331

✨ login page: no redirection if election hasn't started (#225)

---

package.json

Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/election-portal/security/dependabot/35

Security dependencies update

---

package.json

Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/election-portal/security/dependabot/35

Security dependencies update (#227)

---

package.json
yarn.lock

Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/election-portal/security/dependabot/35

Security dependencies update (#229)

---

avElection/layouts/default-election-directive/default-election-directive.html
locales/en.json
locales/es.json

Parent issue: https://github.com/sequentech/meta/issues/550

✨ Fix WCAG Issues and create new report

---

avElection/layouts/default-election-directive/default-election-directive.html
locales/en.json
locales/es.json

Parent issue: https://github.com/sequentech/meta/issues/550

✨ Fix WCAG Issues and create new report (#231)

---

package.json

Parent issue: https://github.com/sequentech/meta/issues/810

🛡 Security updates (#393)

---

avElection/layouts/default-election-directive/default-election-directive.html

Parent issue: https://github.com/sequentech/meta/issues/2667

🐞 Header in login doesn't render html
